### ISSUE TITLE
Change to folder linking?

### ISSUE THREAD

**Issue by stevesbrain** [anishathalye/dotbot#111]
Hey guys, I used to be able to have my install.conf.yaml file look like this for folder linking:

```yaml
- clean: ['~']
- link:
    ~/.vim: 
        create: true
        path: vim/vim_folder
        relink: true
```

However, when I do that now, the installer script throws and error and skips the entire linking block. I've had to change it to:
```yaml
- link:
    ~/.vim: vim/vim_folder/
```

Any reason for this? I couldn't see it mentioned in the changelog. Thanks!

**Comment by anishathalye** [comment]
What's the error message you get?

**Comment by stevesbrain** [comment]
@anishathalye - the total output is as follows:

```bash
$ ./install
All targets have been cleaned
An error was encountered while executing action link
Action link not handled
```

Thanks!

**Comment by anishathalye** [comment]
Huh, your original config (https://github.com/anishathalye/dotbot/issues/111#issue-213215859) works just fine for me. Not sure why it's failing on your system...

If you're curious, you could edit `dotbot/dispatcher.py:33` and add a line right below that like `import traceback; traceback.print_exc()`.

**Comment by stevesbrain** [comment]
Thanks for the suggestion - not sure it's given us too much more info though, haha!

```bash
All targets have been cleaned
An error was encountered while executing action link
NoneType: None
Action link not handled
```

**Comment by anishathalye** [comment]
Wat. Okay, I'm not really sure how to proceed. I can't debug it myself because I can't reproduce it.

If you want to continue investigating, I'm happy to help in any way I can. If you're not interested though, feel free to stop (seems that you have a workaround at least).

**Comment by stevesbrain** [comment]
Whilst I have a workaround, I'd also be keen to help debug just to see what's going on in case it needs fixing for elsewhere! Do you have any other suggestions at the moment? If not, I might see if I can dig down with sysdig or something similar. Thanks @anishathalye :)

**Comment by anishathalye** [comment]
Oh hmm, not sure... probably helpful to print more debugging information / stack traces, or maybe use pdb.

**Comment by reconmaster** [comment]
I've come across this behavior myself when trying to port my dotfiles over to termux. Not really sure what the issue is. As far as I can tell the, link behavior using the old structured layout may have issues with either the filesystem or newline/whitespace encoding. Only android environment seems to be giving me the mess, but let me know if there is any pertinent information I can send your way. No issues with either osx/*nix using the latest on all 3 systems (0618bc70cc98c93cd2faa505585bdd093338f5be).

**Comment by anishathalye** [comment]
Closing this issue due to age. If anyone has new information and/or steps to reproduce, please feel free to reopen.

**Comment by latipun7** [comment]
I've got this error too. My yml config has this line:
```yml
- defaults:
  link:
    create: true
    relink: true
    force: true

- clean: ['~', '~/.config']

- link:
  ~/.bin: linux/bin

- create: [~/projects, ~/downloads]

- shell:
    - [git submodule sync --recursive, Synchronize the URLs of submodules]
    - [git submodule update --init --recursive, Update the submodules]
```

When I run install script, the following verbose output are like this:
```shell
An error was encountered while executing action link
'NoneType' object has no attribute 'get'
Action link not handled
An error was encountered while executing action clean
'NoneType' object has no attribute 'get'
Action clean not handled
An error was encountered while executing action link
'NoneType' object has no attribute 'get'
Action link not handled
Action ~/.bin not handled
Path exists /home/latipun7/projects
Path exists /home/latipun7/downloads
All paths have been set up
An error was encountered while executing action shell
'NoneType' object has no attribute 'get'
Action shell not handled
```
That error msg not very helpful.

I run dotbot install on wsl. My dotfiles directory mounted at drive windows: `/mnt/e/project/dotfiles`.

If you need more info, please let me know. I really have no idea what the cause, no stack trace or something.
