### ISSUE TITLE
Feature request: Flatten lists prior to passing to plugins so that yaml anchors can be used

### ISSUE THREAD

**Issue by dsifford** [anishathalye/dotbot#122]
Hello,

Long time Dotbot user here. Thanks for your hard work on this!

My request is fairly simple. I'm in a situation where I'm jumping between a macbook and a linux machine and I'm using both `dotbot-pacuar` and `dotbot-brew` to maintain a list of my packages for both machines. 

The lists contain, for the most part, the same exact packages with a few here and there differences.

Currently, there's no way to use reference anchors in the plugin yaml file so I have to write my package lists like this:

```yml
- pacaur:
  - package1
  - package2
  - package3
  - package4
  - package5
  - linux-specific1

- brew:
  - package1
  - package2
  - package3
  - package4
  - package5
  - mac-specific1
  - mac-specific2
```

As you can see, there's a lot of unnecesary repeats between both lists.

What I'd like to do instead is this:

```yml
- &common
  - package1
  - package2
  - package3
  - package4
  - package5

- pacaur:
  - *common
  - linux-specific1

- brew:
  - *common
  - mac-specific1
  - mac-specific2
```

This _almost_ works right now, but the hangup is that dotbot doesn't first flatten the lists prior to passing them to the plugins. So what the plugins end up getting is this:

```yml
- pacaur:
  -
    - package1
    - package2
    - package3
    - package4
    - package5
  - 
    - linux-specific1

- brew:
  - 
    - package1
    - package2
    - package3
    - package4
    - package5
  - 
    - mac-specific1
    - mac-specific2
```

Hope that makes sense. Thanks for considering! 😄
