### ISSUE TITLE
Nonexisting target error

### ISSUE THREAD

**Issue by bytemybits** [anishathalye/dotbot#135]
I'm using the latest version (1.11.1) of DotBot and my current setup looks like the following:
```
~/.dotfiles
    dotbot
    install
    install.conf.yaml
```

My `install` file:
```
#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
```

My `install.conf.yaml` file:
```
- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.iterm2: iterm2
    ~/.vscode: vscode

- shell:
  - [git submodule update --init --recursive, Installing submodules]
```

Every time I run `install` I get the message:
```
All targets have been cleaned
Nonexistent target ~/.iterm2 -> iterm2
Nonexistent target ~/.vscode -> vscode
Some links were not successfully set up
Installing submodules [git submodule update --init --recursive]
All commands have been executed

==> Some tasks were not executed successfully
```

I'm using the very much close to default as I could, but clearly I'm missing something...
