### ISSUE TITLE
Linking issues under Windows bash

### ISSUE THREAD

**Issue by prandelicious** [anishathalye/dotbot#137]
I have the following config file:
```
- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- link:
    ~/.gitconfig:
    ~/.gitignore_global:
```
When I run the `install` script, it gives an output:
```
All targets have been cleaned
Linking failed ~/.gitconfig -> C:\Users\user\.dotfiles\gitconfig
Linking failed ~/.gitignore_global -> C:\Users\user\.dotfiles\gitignore_global
Some links were not successfully set up
```
