### ISSUE TITLE
Do not continue if non-zero exit status is returned in shell plugin

### ISSUE THREAD

**Issue by Indy2222** [anishathalye/dotbot#138]
Commands from a single shell list may be dependent on each other and not work properly if earlier commands fail. Furthermore it is sometimes desirable do do a check (e.g. check signature of a downloaded file) before proceeding.

This is currently possible only by putting multiple commands to a single item and calling them like `cmd_a && cmd_b` which creates unnecessary long and hard to read lines.

**Comment by Indy2222** [comment]
I can implement this feature but I am not sure whether this modification is desirable in a greater context I may not have.

**Comment by anishathalye** [comment]
Do you have some example use cases?

I think this could be a useful feature, though it probably shouldn't be enabled by default (it's backwards-incompatible, after all). If it's a setting, what would the API look like?

**Comment by Indy2222** [comment]
Use case:

Emacs can be downloaded in the form of an archive and a signature over plain HTTP. I want to check that the downloaded archive is correctly signed with a trusted public key. See https://www.gnu.org/software/emacs/download.html#gnu-linux.


API can look like this:

```yaml
- shell:
  -
    command: gpg --verify emacs-25.2.tar.gz.sig 2>&1 | grep "28D3 BED8 51FD F3AB 57FE  F93C 2335 87A4 7C20 7910"
    description: Verify GPG signature
    stop_on_error: true
```
