### ISSUE TITLE
fluxbox folder error

### ISSUE THREAD

**Issue by beli3ver** [anishathalye/dotbot#140]
hi,

I tried dotbot, and add to install.conf.yaml

```yaml
   ~/.fluxbox: fluxbox 
```
then I tun `./install -v` but i get this error:

```python
Nonexistent target ~/.fluxbox -> fluxbox
Some links were not successfully set up

==> Some tasks were not executed successfully
```
What did I wrong?

**Comment by beli3ver** [comment]
I updated the file, but it didn't worked
```yaml
    ~/.fluxbox:
        path: fluxbox/
        create: true
        relink: true
        force: true
```
Must I first copy my fluxbox folder to dotfiles?
