### ISSUE TITLE
[Feature] Shell Conditions for all plugins

### ISSUE THREAD

**Issue by robobenklein** [anishathalye/dotbot#143]
I've seen a lot of people wanting to do things like optional tasks, or only run sets of tasks, machine specific configs, etc.

#96, #44 etc.

I think I might have some level of solution.

Here's how an implementation might look:

```yaml
# "Put this only on gaming machines"
- link:
    ~/.steam/someconfig:
      path: gaming/steam/config
      create: false
      condition: [[ -d ~/.steam ]]
```

Link plugin (and perhaps shell plugin) gets additional directive: `condition`,`shellcond`,`shellcondition` or whatever, which is a command that is executed and the return status is used as a boolean. If shell returns true (retval 0) then perform the operation, else don't.

#96 i3 Example:

```yaml
- shell:
  - sudo apt install i3
    condition: ! dpkg -s i3 # using ! as in https://stackoverflow.com/questions/367069/how-can-i-negate-the-return-value-of-a-process
- link:
  ~/.config/i3:
    path: i3
    condition: dpkg -s i3 # success if i3 is installed
```

#44 Shell vars Example:
```yaml
- link:
  ~/.somewhere:
    path: something
    condition: [[ ! -z "$INSTALL_SOMETHING" ]]
```
Could be run as `INSTALL_SOMETHING=1 ./install`

What's the feel for a solution somewhat like this?
