### ISSUE TITLE
"Append" files to a directory

### ISSUE THREAD

**Issue by edgard** [anishathalye/dotbot#16]
Hey!

I wonder if there's an way to install a directory tree without having to symlink the whole destination directory, only the actual files or directories that exists on the source dir.

Something like this:

    ~/.config/terminator:
      create: true
      path: config/terminator/*

The problem I'm dealing with is that there are some unmanaged files being created at the directory after program runs, so I need to keep adding this to a .gitignore everytime.

Is it possible to do something like that, am I missing it somewhere?

**Comment by anishathalye** [comment]
Nope, there's no built-in feature like that.

You could gitignore the specific files that you *don't* want to track.

Or you can use a wildcard gitignore, excluding the specific files that you *do* want to track:

```
# ignore everything
*

# files to track
!.gitignore
!config
!other_file
# ...
```

Or you can use Dotbot to specifically link individual files and not the entire directory:

```yaml
~/.config/terminator/config:
  create: true
  path: config/terminator/config
~/.config/terminator/other_file:
  create: true
  path: config/terminator/other_file
#...
```
