### ISSUE TITLE
Is it possible to glob multiple paths to same destination dir?

### ISSUE THREAD

**Issue by bobwhitelock** [anishathalye/dotbot#179]
Say I have paths I want to glob and symlink in from a couple of different source directories into the same destination directory - in my case I'm in my `dotfiles` repo and I want to link in all files in both a `tmuxinator` directory and a `../dotfiles-private/tmuxinator` directory to `~/.tmuxinator`.

The following doesn't work as the second key just overwrites the first:
```yaml
    ~/.tmuxinator:
        path: tmuxinator/*
        glob: true
        create: true
    ~/.tmuxinator:
        path: ../dotfiles-private/tmuxinator/*
        glob: true
        create: true
```

This also doesn't work, the globbing/symlinking seems to get quite confused by this:
```yaml
    ~/.tmuxinator:
        path: '../dotfiles*/tmuxinator/*'
        glob: true
        create: true
```

Is there any way to do what I want with `dotbot`? Thanks :slightly_smiling_face:

**Comment by bobwhitelock** [comment]
I was able to work around this by using this:
```yaml
    ~/.tmuxinator:
        path: tmuxinator/*
        glob: true
        create: true
    ~/.tmuxinator/:
        path: ../dotfiles-private/tmuxinator/*
        glob: true
        create: true
```
i.e. by having multiple ways of referring to the destination directory which resolve to the same path.

This works fine for me though I guess it wouldn't be very scalable if you needed to do this with many paths being globbed into the same destination.

**Comment by anishathalye** [comment]
Yeah, that's one workaround. Another way you can do it is by having two `link` sections.

```yaml
- link:
    ~/.tmuxinator:
        path: tmuxinator/*
        glob: true
        create: true
- link:
    ~/.tmuxinator:
        path: ../dotfiles-private/tmuxinator/*
        glob: true
        create: true
```
