### ISSUE TITLE
Feature Request: Change link output path with sed|shell

### ISSUE THREAD

**Issue by bpmckee** [anishathalye/dotbot#182]
Vim requires specific naming conventions for functions inside it's autoload directory.
It must be `file#path#filename#FunctionName()`

For example, function `Qux`, defined in a file stored at `~/.vim/autoload/foo/bar/baz.vim` would have to be named `foo#bar#baz#Qux()`.

I like to group everything related to my vim plugins together in a folder.  Because of the strict naming conventions, my custom functions can't be grouped the same way.

Here's my desired setup.
```
dotfiles/
├── vim/
│   └── lib/
│        ├── plug.vim
│        └── settings.vim
│   ├── plugins/
│   │   ├── fzf/
│   │   │   ├── autoload/
│   │   │   │   └── fzf.vim
│   │   │   └── fzf.keymappings.vim
│   │   └── nerd/
│   │        ├── autoload/
│   │        │   └── lib
│   │        │       └── nerdcommenter.vim
│   │        │       └── nerdtree.vim
│   │        └── nerdcommenter.keymappings.vim
│   │        └── nerdcommenter.settings.vim
│   │        └── nerdtree.keymappings.vim
│   │        └── nerdtree.settings.vim
│   └── vimrc
├── tmux/
│   ├── ...
...
```

Here's my desired symlink output:
```
~.vim/
├── autoload/
│   ├── lib/
│   │   ├── nerdcommenter.vim  ---> ~/dotfiles/vim/plugins/nerd/autoload/nerdcommenter.vim
│   │   ├── nerdtree.vim       ---> ~/dotfiles/vim/plugins/nerd/autoload/nerdtree.vim
│   │   ├── plug.vim           ---> ~/dotfiles/vim/lib/plug.vim
│   │   └── settings.vim       ---> ~/dotfiles/vim/lib/settings.vim
│   └──── fzf.vim              ---> ~/dotfiles/vim/plugins/fzf/autoload/fzf.vim
└── ~.vimrc                    ---> ~/dotfiles/vim/vimrc
```

In order to do that, I'd need a way to modify the file path.  Sed would work.  Here's what I'm thinking the `install.conf.yaml` would look like.
```yaml
- link:
    ~/.vimrc: vim/vimrc
    ~/.vim/autoload/:
        create: true
        glob: true
        path: vim/plugins/**/autoload/**/*.vim
        sed: 's/^.*\/autoload\///'
    ~/.vim/autoload/lib:
        glob: true
        path: vim/lib/*.vim
```
If a `sed` command was available, I'd be able to strip off everything before and including the `autoload` directory for each plugin.
