### ISSUE TITLE
Syntax for environment variable in link target

### ISSUE THREAD

**Issue by K41eb** [anishathalye/dotbot#189]
I have been trying to use an environment variable in a `link` target for a while now and I can't figure it out:

From the README:
> Environment variables in paths are automatically expanded.

Is it only true for the `path` extended configuration parameter?

If not how do I make this work:
```yaml
# install.conf.yaml

- link:
    $ZSH_CUSTOM/aliases.zsh:
      path: zsh/aliases
      force: true
```
`$ZSH_CUSTOM` is set, but it appears it is not resolved:
```
Linking failed ($ZSH_CUSTOM/aliases.zsh) -> /home/usr/projects/dotfiles/zsh/aliases
```
