### ISSUE TITLE
`If` condition: `elif` and `else`?

### ISSUE THREAD

**Issue by beuerle** [anishathalye/dotbot#208]
I am trying to use the the `if` entry to link different configuration files depending on the machine (introduced by #169). While a single conditional like

```yaml
- link:
    ~/.gitconfig:
        if: '[ `hostname` = work ]'
        path: git/gitconfig.work
```

works as intended, I do not see how I can implement an `elif` or `else`. If I add another conditional block for `.gitconfig` and/or a default one:

```yaml
- link:
    ~/.gitconfig: git/gitconfig
    ~/.gitconfig:
        if: '[ `hostname` = work ]'
        path: git/gitconfig.work
    ~/.gitconfig:
        if: '[ `hostname` = private ]'
        path: git/gitconfig.private
```

only the last definition is actually executed. If _all_ statements for `~/.gitconfig` would be executed sequentially, this would solve the issue.

Did I miss something here, or is this not possible to do?

Essentially, what I want to do would somehow look like this (emulating the sequential execution):

```yaml
- link:
    ~/.gitconfig:
        if:
            if: '[ `hostname` = work ]'
            path: git/gitconfig.work
        elif:
            if: '[ `hostname` = private ]'
            path: git/gitconfig.private
        else:
            path: git/gitconfig.something
```

**Comment by anishathalye** [comment]
Dotbot does not currently have an elif/else functionality. I think your workaround is the best it can do right now.

More generally, if you ever have an if-else chain of the form `if (P1) A1 elif (P2) A2 ... elif (P{N-1}) A{N-1} else AN`, you can always transform it into a sequence of if statements, `if (P1) A1; if (not P1 and P2) A2; if (not P1 and not P2 and P3) A3 ... if (not P1 and ... and not P{N-1}) AN`, so at least there's a complete and sound way of doing it.

Additionally, I don't think it's possible to add functionality for elif/else in a backward-compatible way in the current syntax. It's plain YAML (so e.g. it can't support multiple `elif` keys), and the interpretation is mostly declarative.

Dotbot 2.0 (#35) could theoretically support this sort of functionality. I think if there's ever a non-backward-compatible version of Dotbot, it'll be implemented as a proper embedded DSL (which is what it's slowly turning into, starting from purely declarative YAML). Some more info in https://github.com/anishathalye/dotbot/issues/206#issuecomment-556901287.

**Comment by beuerle** [comment]
Unfortunately my _workaround_ does not work, as only the last entry is evaluated at all.

I went with actually doing the host distinction in the config file(s) itself. Not as nice, but it gets the job done.

Thanks for the update!

**Comment by anishathalye** [comment]
Oops yeah, that's a good point, I missed that. I think you could work around it by having separate link sections.

```yaml
- defaults:
    link:
      if: '[ `hostname` = work ]'
- link:
    ~/.gitconfig: git/gitconfig.work
    ...

- defaults:
    link:
      if: '[ `hostname` = home ]'
- link:
    ~/.gitconfig: git/gitconfig.home
    ...
```

Though I think doing the distinction in the config file itself is the cleaner solution when it is possible. Imo it also helps with preventing them from getting too out-of-sync.
