### ISSUE TITLE
Variable expansion when displaying 'shell' descriptions

### ISSUE THREAD

**Issue by wirerydr** [anishathalye/dotbot#209]
Given the following install.conf.yaml snippet:
```yaml
- shell:
  -
    command:      mkdir -p user_bin/${USER}@${HOSTNAME%-*.com}
    stdin:        true
    stdout:       true
    description:  Creating user_bin/${USER}@${HOSTNAME%-*.com}
    quiet:        true
```

Displaying the command that will be run is done without parameter expansion (with ```quiet: false```), which is fine.  However the description text is also displayed without parameter expansion, and resembles the following:
```
All targets have been cleaned
Creating user_bin/${USER}@${HOSTNAME%-*.com}
All commands have been executed

==> All tasks executed successfully
```
I have also tried wrapping the description in an echo, like
 **```$(echo "Creating user_bin/${USER}@${HOSTNAME%-*.com}")```**
... but that output also seems to be unexpanded.  Presumably descriptions are printed verbatim without being passed to a sub-process or anything similar.

Could an option be added to dotbot that would allow for descriptions to be first parameter-expanded?  Alternatively, can you suggest a workaround for this that isn't too clunky?  In this specific example, adding the ```--verbose``` option to ```mkdir``` would cause some useful output in the case where the directory was previously nonexistent, however no output is emitted for previously-existing directories.  Also, that doesn't cover commands other than ```mkdir```.

Thank you very much

- WireRydr
