### ISSUE TITLE
Action create not handled

### ISSUE THREAD

**Issue by Stunkymonkey** [anishathalye/dotbot#210]
my current file starts like this:
```
- defaults:
    link:
        relink: true

- clean: ['~']

- create:
    - ~/.profile.d
    - ~/.local/bin
    - ~/.config/alacritty
    - ~/.config/htop
    - ~/.config/i3status
    - ~/.config/mako
    - ~/.config/redshift/hooks
    - ~/.config/rofi
    - ~/.config/sway
    - ~/.config/swaylock
    - ~/.config/yay
    - ~/.vim/pack/dotfiles

# casual
- link:
    ~/.dotfiles: ''
    ~/.bashrc: bash/bashrc
    ~/.bash_profile: bash/bashrc
...
```
but it always outputs `Action create not handled`. So no folders are created.
Even the example from the README.md does not work for me.

maybe you could add a better explanation of the yaml configuration, because i do not see the problem.
