### ISSUE TITLE
make list config optional?

### ISSUE THREAD

**Issue by mohkale** [anishathalye/dotbot#213]
I understand the reason for a config being a list, but in my case I don't really need to specify a directive more than once in the config. Because of this, having to prefix every directive with `- ` seems unnecessary.

Thus I suggest allowing simple hash based configs, ergo turning:

```yaml
- defaults:
    link:
      relink: true
      create: true

- clean: ['~']

- create:
    - ~/downloads
    - ~/multimedia
```

into:

```yaml
defaults:
  link:
    relink: true
    create: true

clean: ['~']

create:
  - ~/downloads
  - ~/multimedia
```

I believe this should be pretty easy to implement in `dotbot/cli.py` using the following diff.

```diff
diff --git a/dotbot/cli.py b/dotbot/cli.py
index 77bd439..d005293 100644
--- a/dotbot/cli.py
+++ b/dotbot/cli.py
@@ -70,8 +70,10 @@ def main():
             log.error('No configuration file specified')
             exit(1)
         tasks = read_config(options.config_file)
-        if not isinstance(tasks, list):
-            raise ReadingError('Configuration file must be a list of tasks')
+        if isinstance(tasks, dict):
+            tasks = [{key: value} for key, value in tasks.items()]
+        elif not isinstance(tasks, list):
+            raise ReadingError('Configuration file must be a list or hash of tasks')
         if options.base_directory:
             base_directory = os.path.abspath(options.base_directory)
         else:
```
