### ISSUE TITLE
merge defaults, instead of overwriting them

### ISSUE THREAD

**Issue by mohkale** [anishathalye/dotbot#216]
I see in [dispatcher](https://github.com/anishathalye/dotbot/blob/master/dotbot/dispatcher.py#L25) that you've commented the line which sets defaults to `# replace, not update`. Is there a reason for this?

I feel it's a pretty normal use case to have multiple defaults:

```yaml
- defaults:
    link:
      create: true

# make some links

- defaults:
    link:
      force: true

# replace some existing links
```

Disregard the fact the `force` implies `create` for this example and instead consider that someone wants to add new defaults for link, while maintaining their previous ones. Having to re specify them feels needlessly cumbersome.

**Comment by anishathalye** [comment]
I think merging defaults complicates the semantics even more, because it requires even more non-local reasoning.

Without defaults, all you need is to read a particular line to understand what it will do.

```yaml
- link:
    foo: bar
```

With defaults (as it is currently implemented), you need to read the particular line, along with the nearest `defaults`:

```yaml
- defaults:
    link:
      create: true
- link:
    foo: bar
```

With merging defaults, it requires reading the whole line for all the defaults, and "integrating".

Aside from this, I actually imagine that most configs make 0 or 1 uses of `defaults`. In any case, we wouldn't be able to change this until a v2.0, where we make backward-incompatible changes.
