### ISSUE TITLE
Shell command with quiet option set to false is still being suppressed 

### ISSUE THREAD

**Issue by vai0** [anishathalye/dotbot#223]
```yaml
...
- shell:                                                                                            
  -                                                                                               
    command: cat .vscode/extensions.txt | xargs -L 1 echo code --install-extension | bash       
    description: Install VSCode extensions                                                            
    quiet: false
```
output of running `./install`
```bash
All targets have been cleaned
Link exists ~/.bash_profile -> /home/jchi/.dotfiles/bash_profile
Link exists ~/.bashrc -> /home/jchi/.dotfiles/bashrc
Link exists ~/.gitconfig -> /home/jchi/.dotfiles/gitconfig
Link exists ~/.vimrc -> /home/jchi/.dotfiles/vimrc
Link exists ~/.zshrc -> /home/jchi/.dotfiles/zshrc
Link exists ~/.config/nvim/init.vim -> /home/jchi/.dotfiles/init.vim
~/.config/Code/User/keybindings.json already exists but is a regular file or directory
~/.config/Code/User/settings.json already exists but is a regular file or directory
Some links were not successfully set up
Install VSCode extensions [cat .vscode/extensions.txt | xargs -L 1 echo code --install-extension | bash]
All commands have been executed

==> Some tasks were not executed successfully
```
Some info:
- dotbot version: commit `* f5e0191 - Work around subprocess.call() issue on Windows`
- system: Debian GNU/Linux 10 (buster)
config file:
```yaml
- clean: ['~']

- link:
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.gitconfig: gitconfig
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.config/nvim/init.vim: init.vim
    ~/.config/Code/User/keybindings.json: .vscode/keybindings.json
    ~/.config/Code/User/settings.json: .vscode/settings.json

- shell:
    -
        command: cat .vscode/extensions.txt | xargs -L 1 echo code --install-extension | bash
        description: Install VSCode extensions
        quiet: false
```
