### ISSUE TITLE
Action link not handled

### ISSUE THREAD

**Issue by zapme** [anishathalye/dotbot#232]
OS: Freebsd 12.1

Command output
```
./install -v
All targets have been cleaned
An error was encountered while executing action link
'NoneType' object has no attribute 'items'
Action link not handled
Action ~/.tmux.conf not handled
Installing/updating submodules [git submodule update --init --recursive]
All commands have been executed

==> Some tasks were not executed successfully
```

```
./install --version
Dotbot version 1.17.1 (yaml: 5.3)
```

Python version
```
python3 --version
Python 3.7.8
```

install.conf.yaml
```
- clean: ['~']


- link:
  ~/.tmux.conf:
    path: tmux.conf
    relink: true
    force: true


- shell:
  - [git submodule update --init --recursive, Installing/updating submodules]
```

**Comment by anishathalye** [comment]
Your YAML is slightly incorrect. Here's what the YAML given above [converts to](https://www.json2yaml.com/):

```json
[
  {
    "clean": [
      "~"
    ]
  },
  {
    "link": null,
    "~/.tmux.conf": {
      "path": "tmux.conf",
      "relink": true,
      "force": true
    }
  },
  {
    "shell": [
      [
        "git submodule update --init --recursive",
        "Installing/updating submodules"
      ]
    ]
  }
]
```

It's a bit unfortunate that YAML is so complicated, and these tiny whitespace things can cause issues. Not entirely sure how to improve on it, though.

For your particular case, you need a bit more indentation:

```yaml
- clean: ['~']


- link:
    ~/.tmux.conf:
      path: tmux.conf
      relink: true
      force: true


- shell:
  - [git submodule update --init --recursive, Installing/updating submodules]
```

I think this should give the correct results.
