### ISSUE TITLE
Shell commands after install

### ISSUE THREAD

**Issue by gtrias** [anishathalye/dotbot#24]
Could be great to have the option to specify shell commands to be executed after all other actions, normal shell execution, links and clean.

That way we can execute additional shell commands after we have all the files deployed. For example we could change permissions of some folders not staged on repository.. Compile some package source, and so on.

**Comment by anishathalye** [comment]
Dotbot supports this already. You're allowed to use the `shell` directive more than once.

For example:

```yaml
- shell:
  - touch ~/.testfile
- link:
    ~/.vimrc: vimrc
- shell:
  - rm ~/.testfile
```
