### ISSUE TITLE
Add ability to exclude glob matches

### ISSUE THREAD

**Issue by etkeys** [anishathalye/dotbot#247]
Suppose I have the following repository

```txt
config/autostart/a.desktop
config/autostart/b.destkop
config/autostart/c.desktop
config/Awesome_App/settings.conf
config/Code/User/snippets/snippet1.snippet
config/Code/User/keybindings.json
config/Code/User/settings.json
config/i3/config
config/Random_App/settings.ini
install
install.conf.yaml
```

with the following `install.conf.yaml` file:

```yaml
- defaults:
    - link:
        create: true
        force: true
        relink: true

- clean:
    ~/:
        force: true
    ~/.config:
        recursive: true

- link:
    ~/.config/:
        path: config/*/*
        glob: true
```

After execution I will have symlinks to all the files specified and `~/.config/Code/User` will be a directory symlink to `config/Code/User`. All well and good, this is expected behavior. However, this is not how I want `~/.config/autostart` and `~/.config/Code/User` setup. I would like a means to be able to use the `config/*/*` globbing but also be able to specify a globbing pattern to exclude. This will allow me to specify more appropriate link actions for `config/autostart` and `config/Code/User` while keeping a more general catch all pattern with handles the majority of cases.

Here is a possible new version of `install.conf.yaml` using this exclusion:

```yaml
# defaults and clean are unchanged

- link:
    ~/.config/:
        path: config/*/*
        glob: true
        exclude: [config/autostart/*, config/Code/*]
#           - config/autostart/*
#           - config/Code/*
    ~/.config/autostart: config/autostart
    ~/.config/Code/User/:
         path: config/Code/User/*
         glob: true
```

From here, dotbot could use the patterns in `exclude` to generate a list of files using the same glob mechinisms that generates the targets list and then just perform set difference to get the final list. As a bonus, adding `exclude` paremeter does not break backwards compatibility :)

If there is no problem with this suggestion, I would like to implement this.
