### ISSUE TITLE
add `mode:` option to `create:` directive

### ISSUE THREAD

**Issue by eengstrom** [anishathalye/dotbot#260]
The `create:` directive allows creation of directories, but it doesn't allow the specification of the mode.  This is important in some cases, for example for `~/.ssh`, which should be `0700` (non-readable by group/world).  

I would suggest adding something like this:

```yaml
- create:
    ~/.ssh:
      mode: 0700
      # or something symbolic
      mode: u+rwx,go-rwx
```

As a workaround for now, I'm combining `create:` with `shell:`

```yaml
- shell:
  - command: chmod 0700 ~/.ssh
```
