### ISSUE TITLE
`if` no longer works?

### ISSUE THREAD

**Issue by magicalbanana** [anishathalye/dotbot#263]
```
 a517c4c5d0b6bdd8ab3a62f3c6c3f38837354bde dotbot (v1.11.1-9-ga517c4c)
```

Using `if` like so:

```
    ~/.tmux.conf:
        relink: true
        force: true
        path: tmux/tmux.conf
    ~/.tmux.conf:
        if: '[[ `uname` == "Darwin" ]]'
        relink: true
        force: true
        path: tmux/tmux.osx.conf
```
seems like to not work anymore because even though I am using Linux, my tmux for OSX gets linked?

**Comment by anishathalye** [comment]
That is an old version of Dotbot that doesn't support `if`. The support for `if` was introduced in `1b17e8e (v1.13.0-3-g1b17e8e)`.

I recommend you just upgrade to the latest version.

**Comment by rafifos** [comment]
@anishathalye I'm also having this issue:

> config.yaml
```yaml
- defaults:
    link:
      create: true
      force: true
      relative: true

- clean: ["~", "~/.config"]

- link:
    ~/.config/git/user-rafifos.conf:
      if: '[[ $HOSTNAME = "GUARDIAN" ]]'
      path: git/includes/user-rafifos.conf
```

> Output:
```shell-session
rafifos@GUARDIAN:~/.dotfiles$ ./.dotbot/bin/dotbot --version
Dotbot version 1.18.0 (yaml: 5.3)
rafifos@GUARDIAN:~/.dotfiles$ "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}" --verbose
Test '[[ $HOSTNAME = "GUARDIAN" ]]' returned false
Skipping ~/.config/git/user-rafifos.conf
```
