### ISSUE TITLE
Glob fails to link if there's only one file

### ISSUE THREAD

**Issue by jwpeddle** [anishathalye/dotbot#282]
When I try to use glob with only one file in the source directory, dotbot fails to create the link with "Nonexistent source for.."

```
- defaults:
    link:
      relink: true
      glob: true
      force: true
- link:
    ~/.config/broot: broot/*
```
```
.
├── broot
│   └── conf.hjson
```

```
❯ ./install 
Nonexistent source for ~/.config/broot : /home/jay/dotfiles/broot/*

==> Some tasks were not executed successfully
```
Adding a second file without changing anything else makes it function as expected. I would expect it to behave the same regardless of how many files are in the dir. 

Why bother using glob if there's only one file? Because it means if I add a second file later, I don't need to also edit my install.conf.yaml. Almost always, I just want to symlink _whatever_ is in the source directory. It took some squinting to even identify what was going wrong.
