### ISSUE TITLE
Add Option to Ignore "Globbing couldn't find anything matching"

### ISSUE THREAD

**Issue by patbakdev** [anishathalye/dotbot#284]
I have the following config with the intention of being able to just drop in files/folders and have them automatically picked up. But if some folders are empty, then I get the warning ("Globbing couldn't find anything matching ...") and exit code 1. I'd like to have an option to ignore this warning and return exit code 0.

```
- defaults:
    link:
      create: true
      relink: true
      glob: true

- clean:
    - ~/
    - ~/.config
    - ~/.local
    - ~/.local/bin

- link:
    ~/:
      path: ./.*
      exclude:
        - ./.config
        - ./.local
    ~/.config/:
      path: ./.config/*
    ~/.local/:
      path: ./.local/*
      exclude:
        - ./.local/bin
    ~/.local/bin:
      path: ./.local/bin/*
```

Perhaps something like:
```
- link:
    ~/:
      path: ./.*
      ignore_empty_glob: true     <-- NEW
      exclude:
        - ./.config
        - ./.local
```
