### ISSUE TITLE
Exit on failure

### ISSUE THREAD

**Issue by ssbanerje** [anishathalye/dotbot#288]
Is there an option I can set to have the `dotbot` script exit on failure of a command. The current behavior seems to be to keep executing the remaining directives even if one of the intermediate steps fails.

**Comment by anishathalye** [comment]
No, this option does not currently exist, but I am open to adding it. What would be a good interface? Having a command-line flag, e.g. `-e/--exit-on-error`?

Another option would be to put it in the config file, though the yaml config file doesn't currently have any options to configure Dotbot itself, so we'd need to figure out what the interface for that should look like. Should there be a `dotbot:` section? Or perhaps have it be a part of the defaults, like:

```yaml
- defaults:
    dotbot:
      exit-on-error: true
    link:
      create: true
      # ...
```
