### ISSUE TITLE
The configuration in a single-line profile will not run unless there is an empty line at the end of the file

### ISSUE THREAD

**Issue by Vafa-Andalibi** [anishathalye/dotbot#297]
Just noticed this behavior when my test profile had just one configuration and dotbot was skipping it and wasn't performing any operation. After adding a new line at the end of the profile, it started working again.

**Comment by anishathalye** [comment]
If there's nothing sensitive in the file, could you share the problematic config file itself? That would help me reproduce/debug the issue.

**Comment by Vafa-Andalibi** [comment]
Sure this is the `base-clean.yaml` in config folder: 

```
- defaults:
    link:
      create: true
      force: true

- clean: ['~']

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- create:
    - ~/Downloads
    - ~/.vim/undo-history
- create:
    ~/.ssh:
      mode: 0700
    ~/gitrepos:
```

This is `generic_device` in the `profile` folder (note that there is no empty line at the end): 

```
base-clean
```
