### ISSUE TITLE
feature-request: run a command **IF** a condition passes

### ISSUE THREAD

**Issue by Clumsy-Coder** [anishathalye/dotbot#312]
just like **[LINK](https://github.com/anishathalye/dotbot#format)** directive, there should one for running individual commands for SHELL directive.

Ex:
```yaml
- shell:
    - command: apt update && apt upgrade -y
      if: lsb_release -i | grep -io 'debian'
      description: Update APT package repository

    - command: dnf update -y
      if: lsb_release -i | grep -io 'fedora'
      description: Update DNF package repository
```

## why
- provides a better flow of running dotbot process
- can contain similar commands in a single shell directive. 
  - Ex: shell directive for updating repositories
  - Ex: installing a package using package manager in one OS, downloading a script from another OS
