### ISSUE TITLE
Command output for conditionals appears to fail for Git Bash

### ISSUE THREAD

**Issue by matthew-brett** [anishathalye/dotbot#316]
Please forgive me if I misunderstood the syntax, but I have a clause in my install file for Windows installs:

```yaml
    ~/Documents/WindowsPowerShell/Profile.ps1 :
      path: Profile.ps1
      if: '[ $(command -v powershell) ]'
```

This always skips.   Investigating, this version of the `if` clause does not skip:

```yaml
      if: '[ -d "/c/Windows/System32" ]'
```

nor does this:

```yaml
    if '[ `echo` ]'
```

but this does:

```yaml
      if: '[ `echo yes` ]'
```

On the other hand, if I run this from the Git Bash shell, I get the expected "is true" output:

```
$ if [ `echo yes` ]; then echo 'is true'; fi
```

Is there something specific going on in Git Bash and the conditional clauses here?
