### ISSUE TITLE
[Errno 2] No such file or directory: 'install.conf.yaml'

### ISSUE THREAD

**Issue by mfoulds** [anishathalye/dotbot#320]
I just installed dotbot as per [this tutorial](https://www.elliotdenolf.com/posts/bootstrap-your-dotfiles-with-dotbot) and receive the following error when running `install`:

```
~/.dotfiles$ ./install
Could not read config file:
  [Errno 2] No such file or directory: 'install.conf.yaml'
```

folder contents are:

```
.dotfiles/
┣ dotbot/
┣ .bashrc
┣ .condarc
┣ .gitmodules
┣ README.md
┣ install
┗ install.config.yaml
```

install.config.yaml contents:

```
- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.bashrc: bashrc
    ~/.condarc: condarc

- shell:
  - [git submodule update --init --recursive, Installing submodules]

```

Any ideas?
