### ISSUE TITLE
'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by dylode** [anishathalye/dotbot#322]
Config:

```
- defaults:
    link:
      create: true
      relink: true

- create:
    - ~/Projects
    - ~/.config

- link:
    - ~/.config/alacritty: alacritty

- shell:
  - [git submodule update --init --recursive, Installing submodules]
 ```

Command:
```
> ./install -v
Path exists /home/dylan/Projects
Path exists /home/dylan/.config
All paths have been set up
An error was encountered while executing action link
'list' object has no attribute 'items'
Action link not handled
Installing submodules [git submodule update --init --recursive]
All commands have been executed

==> Some tasks were not executed successfully
```
