### ISSUE TITLE
Trying to link a file from a submodule into a subdirectory of a directory managed by dotbot

### ISSUE THREAD

**Issue by StFS** [anishathalye/dotbot#337]
I have a directory that I mange with dotbot:

```
- link:
  ~/.vim: vim/
```

I also have a submodule in my dotfiles repo:

```
dotfiles/vim-modules/pathogen
```

Inside this submodule, there is a file (`pathogen/autoload/pathogen.vim`) that I need to place in `~/.vim/autoload/pathogen.vim` so that vim autoloads that plugin.

I've tried doing it like this (trying to symlink the file from the submodule into the dotfiles vim directory so that the `~/.vim/` symlink will have it included):

```
- link:
    ~/.vim: vim/
    vim/autoload/pathogen.vim:
      create: true
      path: vim-modules/pathogen/autoload/pathogen.vim
```

But this is not working.

The error I'm getting is:

```
Nonexistent source vim/autoload/pathogen.vim -> vim-modules/pathogen/autoload/pathogen.vim
```

Is there some way to make dotfiles create a symlink inside the dotfiles directory itself?

I hope I'm making myself understood here... but probably not... sorry about that 😞
