### ISSUE TITLE
Allow execution of commands send data through STDIN

### ISSUE THREAD

**Issue by pabloferz** [anishathalye/dotbot#53]
I was trying to set the installation of my vim plugins in the `install.conf.yaml`file. Unfortunately, that does not work.

I am using `vim-plug` to handle vim plugins, so I added `vim +PlugInstall +qall` as a shell command, but it fails. I believe that is because of this line

    ret = subprocess.call(cmd, shell=True, stdin=stdin, stdout=stdout,
                          stderr=stderr, cwd=self._base_directory)

in the `commandrunner.py` script. A possible solution would be setting `stdin=subprocess.PIPE`, but I'm not sure if that posses a problem in some scenario.

**Comment by pabloferz** [comment]
By the way, thank you for the tool. I love the simplicity of it.

**Comment by bchretien** [comment]
I am also using dotbot to do the exact same thing. Here's how you can do it:

```yaml
- shell:
    # Install vim plugins
    -
      command: vim -Nu ~/.vimrc.plugins +PlugUpdate +qall &> /dev/null
      stdin: true
      stdout: true
      stderr: true
```

(my vim-plug entries are in a separate `.vimrc.plugins`, but using a unique `.vimrc` would not change anything)

If you don't want it to be done silently in the background, remove the `/dev/null` redirection.
