### ISSUE TITLE
Platform specific link paths

### ISSUE THREAD

**Issue by ToJa92** [anishathalye/dotbot#57]
Hello, I've been using dotbot to manage my dotfiles for some time now.
It has worked great thus far, since most applications read from a common configuration directory on all platforms. Sublime Text however, uses different directories depending on what platform you're on.

Would it be feasible to add support for different destination paths depending on your OS?
In Python there's `sys.platform` which contains a string representing the platform Python is running on.

As for configuration syntax, I'm not sure.
YAML has a construct where you can map keys to values, [see example 2.6](http://www.yaml.org/spec/1.2/spec.html#id2759963), but since dotbot maps links "the other way", the syntax wouldn't make sense (and is syntactically incorrect):

```
- link:
    {
     linux: ~/.config/sublime-text-3,
     darwin: ~/Library/Application Support/Sublime Text 3,
     win32: ~/Sublime Text 3
    }: Sublime Text 3/
```

If you flip the target and destination, I think it looks decent and you would still be able to configure links independently of the OS/platform. It would obviously break all existing configuration files, however.

```
- link:
    Sublime Text 3/:
      linux: ~/.config/sublime-text-3,
      darwin: ~/Library/Application Support/Sublime Text 3,
      win32: ~/Sublime Text 3
    vim/: ~/.vim
```

What do you think?

**Comment by anishathalye** [comment]
Cool idea. Yeah, the `from: to` vs `to: from` change isn't a big deal, but yeah, it would break backwards compatibility, so a change like this would have to wait until 2.x.

This is kinda sorta possible already (https://github.com/anishathalye/dotbot/pull/11#issuecomment-73082152), but it's not the cleanest way of doing it.

**Comment by sjthespian** [comment]
I'll throw in another vote for this feature with a slight twist. It would be nice to not only be able to have os-specific links, but also install config files for some applications only on the systems that support them, for example only installing my hammerspoon config if I'm on a Mac.

I think the config example above is along the lines of what I am thinking. If a platform isn't listed, the link won't be created on that platform and you would need a way to specify a default in some cases. for example:
```yaml
- link:
  ~/.bashrc:
    platforms:
      - name: default
        path: bashrc     
      - name: debian
        path: bashrc-debian   
  ~/.hammerspoon:
    platforms:
      - name: darwin
        path: hammerspoon
```

**Comment by robobenklein** [comment]
Apparently this can also be solved with the shell conditions feature (https://github.com/anishathalye/dotbot/issues/143):

For your example @sjthespian 
```yaml
- link:
  ~/.bashrc:
    path: bashrc
    if: '[ ! -f "/etc/debian_version" ]'
  ~/.bashrc:
    path: bashrc-debian
    if: '[ -f "/etc/debian_version" ]'
  ~/.hammerspoon:
    path: hammerspoon
    if: '[[ "$(uname)" == "Darwin" ]]'
```

Does that sound right?

**Comment by sjthespian** [comment]
@robobenklein That's perfect, I didn't realize it supported conditionals! I just gave it a try and this works for me. This actually means I can combine all my yaml files and let the system figure it out. Thanks!!

```
    # Mac files
    ~/.hammerspoon:
      path: hammerspoon
      if: '[ -f "/Applications/Hammerspoon.app" ]'
    ~/bin/it2cmd:
      path: bin/it2cmd
      if: '[ -f "/Applications/iTerm.app" ]'
```

**Comment by robobenklein** [comment]
Glad that works! If you notice any other issues please let me know because I plan to clean it up and make a PR for it soon!

**Comment by sjthespian** [comment]
@robobenklein The way you've written it is great, as you can pass arbitrary commands to it. For example, I can install files on my home systems only with something like:
```
- linkif:
    #
    # Home
    ~/.bashrc.d/dosomething.sh:
      create: true
      path: bashrc.d/dosoemthing.sh
      if: 'hostname -f | grep myhomedomain.com > /dev/null'
```

Of course, even better would be to use:
```
      if: '[[ $(hostname -f) =~ myhomedomain.com$ ]]'
```
(which also works)

**Comment by njunxuan** [comment]
`if` does not seem to be working well for me. I have this in my config:
```
    ~/.config/alacritty/alacritty.yml:
        create: true
        path: alacritty/alacritty.mac.yml
        if: '[[ "$(uname)" == "Darwin" ]]'
    ~/.config/alacritty/alacritty.yml:
        create: true
        path: alacritty/alacritty.linux.yml
        if: '[[ "$(uname)" == "Linux" ]]'
```
And dotbot links the my linux config despite me being on my MacBook.

**Comment by njunxuan** [comment]
> Apparently this can also be solved with the shell conditions feature (#143):
> 
> For your example @sjthespian
> 
> ```yaml
> - link:
>   ~/.bashrc:
>     path: bashrc
>     if: '[ ! -f "/etc/debian_version" ]'
>   ~/.bashrc:
>     path: bashrc-debian
>     if: '[ -f "/etc/debian_version" ]'
>   ~/.hammerspoon:
>     path: hammerspoon
>     if: '[[ "$(uname)" == "Darwin" ]]'
> ```
> 
> Does that sound right?

It seems that it's not possible to do what you did with `.bashrc`. As long as one of the test fails, dotbot will skip the linking for both of them.

**Comment by anishathalye** [comment]
The issue @njunxuan points out has to do with YAML / the data format. The data under `link:` is a dictionary, so if there are duplicate keys, one of them is going to get clobbered.

A workaround would be to write it like this:

```
- link:
  ~/.bashrc:
    path: bashrc
    if: '[ ! -f "/etc/debian_version" ]'
- link:
  ~/.bashrc:
    path: bashrc-debian
    if: '[ -f "/etc/debian_version" ]'
  ~/.hammerspoon:
    path: hammerspoon
    if: '[[ "$(uname)" == "Darwin" ]]'
```

**Comment by njunxuan** [comment]
Thanks for the work around! I'll poke around the code too and see what can be done to resolve this.

**Comment by anishathalye** [comment]
It can't be fixed unless we want to change the interface. It's an issue with the YAML/JSON spec. Dictionaries are functions, so they don't allow a key to map to multiple values. A YAML/JSON object cannot represent e.g. the mapping `a->b; a->c`.

**Comment by njunxuan** [comment]
I see. I guess the way forward would be to have one link segment for linux and another for mac then.

**Comment by anishathalye** [comment]
Yeah. You can actually update the defaults in between. For example:

```yaml
- defaults:
    link:
      if: # is mac
- link:
    # all mac links
- defaults:
    link:
      if: # is linux
- link:
    # all linux links
```
