### ISSUE TITLE
Why is ~/.dotfiles: '' necessary?

### ISSUE THREAD

**Issue by sunnyrjuneja** [anishathalye/dotbot#78]
Hi Anish,

Thanks for your invaluable tool. I'm just getting started and dotbot seems like a great piece of software :+1:.

Quick question, I noticed on a lot of people's configs that the following line appears.

```
~/.dotfiles: ''
```

What does it do? Why is it necessary?

My dotfiles are stored in: `~/notebook/dotfiles` and when I include `~/notebook/dotfiles: ''`

the following error appears in my output:

```
~/notebook/dotfiles already exists but is a regular file or directory
```

What am I doing wrong?

By the way, I'm on Ubuntu 14.04 and python -v outputs 2.7.6.

Full install.conf.yaml
```
- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/notebook/dotfiles: ''
    ~/.vimrc: vimrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
```
