### ISSUE TITLE
Using relink or force with relative always removes before linking

### ISSUE THREAD

**Issue by anishathalye** [anishathalye/dotbot#85]
The following config results in deleting and relinking the file every time the script is run:

```yaml
- defaults:
    link:
      relink: true
      relative: true

- link:
    ~/.ssh/conf.d/foo.conf:     ssh/conf.d/foo.conf
```

See https://github.com/anishathalye/dotbot/issues/70#issuecomment-205488166 for more information
Reported by @sjthespian
