### ISSUE TITLE
Linking a file from $HOME

### ISSUE THREAD

**Issue by Lindenk** [anishathalye/dotbot#93]
Hello!

So, I have several configs that I'm trying to concatinate into a single file to be the final config. While this is pretty easy to do with shell commands, I also want to keep it 'tracked' by dotbot as usual and never accidentally overwrite or alter an existing file. The relevant .conf.yaml is:

```yaml
# Xresources
- shell:
    - mkdir -p $HOME/.config/X
    - ">| $HOME/.config/X/.Xresources"
- link:
    ~/.Xresources:
        relative: false
        path: ~/.config/X/.Xresources

# URxvt
- shell:
    - [cat desktop/urxvt/.Xresources >> $HOME/.config/X/.Xresources, 
        Adding URxvt to .Xresources]
```

However, it seems that `path: ~/.config/X/.Xresources` evaluates to `/path/to/dotfiles/~/.config/X/.Xresources`, even with `relative: false`. I could provide an absolute path, but I don't want to hard code my user into my dotfiles. `$HOME` also doesn't work because, to my knowledge, environment variables do not get resolved in non-shell-commands. I suppose the best solution is to link it manually, but I first I wanted to see if I'm just missing something obvious.

**Comment by anishathalye** [comment]
Hm, so that's not the way relative works. Setting `relative: true` will make it so that the generated file path is relative to the target.

So, suppose I have my dotfiles in `/home/anish/dotfiles`.

If I use:

```yaml
- link:
    ~/.zshrc:
      path: zshrc
      relative: false
```

Then it'll link `~/.zshrc -> /home/anish/dotfiles/zshrc`.

If I use `relative: true` in the example above, it'll link `~/.zshrc -> dotfiles/zshrc`.

---

For your use case, if you do:

```yaml
- link:
    ~/.Xresources: $HOME/.config/X/.Xresources
```

It will work.

Thanks to your post, I just discovered that there is a bug where envvars aren't expanded in the expanded config. (I'm working on fixing the bug right now.)
